### PR TITLE
German translation: nondiscriminatory language

### PR DESCRIPTION
**Pull request by stiglers-eponym**
The original German translation explicitly addresses male players, which
in conservative reading of German language is meant to address everyone.
The changes in this commit replace this by a gender-neutral language.
There is no universal consensus in Germany concerning gender-neutral
language and some conservative readers might prefer the "traditional"
wording. But discrimination-free language is no longer just a political
topic but also part of everyday live in Germany.

Changes also address a grammar mistake in the German translation
(line 99: "unschuldigen" instead of "unschuldiger").

I do not intend to start a long discussion if you really don't want these changes.

### CODE REVIEW

**Comment by benjamintd** [comment]
Hi @stiglers-eponym . Thanks for your contribution! I am not familiar with the gender-neutral language consensus in Germany, but I assume it is similar to the one in France. Some people use it and some more conservative ones find it hard to read and unnecessary. 

I don't believe it's my call to make since I'm unfamiliar with the issue specifically in Germany. 

Perhaps the original translator @mwkroening can chime in and let me know if that's good to merge?

**Comment by mwkroening** [comment]
Thanks for your work, @stiglers-eponym!

Though I don't find this practice unnecessary, I do find it harder to read in this case. In my experience, which might not be up to date, game manuals try to be simple using the generic masculine. It might be favorable to reformulate some sentences to avoid this problem, but in others this `:` construction might be the best solution. The proposed change is definitely an improvement in gender-neutral language. :+1:

What do you think?

**Comment by stiglers-eponym** [comment]
Thanks for taking this serious. I read though it again and simplified a few formulations. The version from last night did include some unnecessarily complicated formulations. I hope this makes it better now.

**Comment by benjamintd** [comment]
I'm deploying a preview link so that you can see how this formulates in context. 

@mwkroening @stiglers-eponym if you both agree to merging this in the current state, give me a 👍 and I'll press the green button :) 

Thank you!

**Comment by stiglers-eponym** [comment]
I found one more tiny mistake and will read through it again, expect my commit in 5 minutes.

**Pull request merged**
